language: cpp

compiler:
  - clang
  - gcc

before_script:
  - echo "before script"

script: make

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a9ab298bd264c71a2eed
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

