language: cpp
#run on latest container based infrastructure
sudo: false

compiler:
  - clang
  - gcc

#workaround for container based packages
addons:
  apt:
    packages:
    - gfortran
    - openmpi-bin
    - openmpi-common
    - libopenmpi-dev

before_install:
  - echo "not using sudo"
#  - apt-get install -q gfortran openmpi-bin openmpi-common libopenmpi-dev;

#create the bin directories
before_script:
  - mkdir client/bin
  - mkdir server/bin
  - mkdir client/obj
  - mkdir server/obj
  - MPIEXEC='mpiexec'

script: make

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a9ab298bd264c71a2eed
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

